apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: venafi-issuer
  namespace: example
spec:
  venafi:
#  Cloud setup
    apikey: "ab3344ff-7ba0-448e-bf0d-f27d73d7b78d"
    zone: "Default"
#  TPP setup
#    url: "https://192.168.4.98/vedsdk"
#    tppuser: "admin"
#    tpppass: "newPassw0rd!"
#    zone: "Certificates\\arykalin"

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoserver
  namespace: example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: example
  labels:
    app: echoserver
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
